site_name: Kalp Studio Documentation
site_author: Siddhesh Patankar
copyright: Copyright © 2024 Kalp studio. All rights reserved.
repo_url: https://github.com/p2eengineering/kalp-studio-documentation
site_url: https://doc.kalp.studio/
repo_name: Kalp-studio-documentation

theme:
  extra_css:
    - stylesheets/extra.css
  font:
    text: Source Sans 3, sans-serif
  name: material
  logo: images/PNG.png 
    #- link: Introduction/welcome.md
  favicon: images/PNG.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - header.bold
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant
    - navigation.instant.progress
    # - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.leftside
    - navigation.tracking
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      accent: deep orange
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/eye-outline
        name: Switch to system preference
  plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: false
  - search
  - open-in-new-tab
  - git authors
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

#  markdown_extensions:
#  - pymdownx.highlight:
#      anchor_linenums: true
#      line_spans: __span
#      pygments_lang_class: true
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences
#  - pymdownx.highlight
#  - pymdownx.inlinehilite
#  - pymdownx.keys

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Introduction: 
          - Kalp studio overview: 'Introduction/Kalp-studio-overview.md'
          - Kalp studio ecosystem: 'Introduction/Kalp-studio-ecosystem.md'
          - What is smart contract deployer: 'Introduction/What-is-kalp-instant-deployer.md'
          - What is kalp studio wallet: 'Introduction/What-is-kalp-studio-wallet.md'
          - Kalp DLT: 'Introduction/Kalp-DLT.md'
  - Getting started:
      - Onboarding:
          - How to Sign Up and Log In to Kalp Studio Platform: 'Getting-started/Onboarding/How-to-Sign-Up-and-Log-In-to-Kalp-Studio-Platform.md'
          - How to Change the Password: 'Getting-started/Onboarding/How-to-Change-the-Password.md'
      - Dashboard:
          - How to Navigate Kalp Studio Platform as a New User: 'Getting-started/Dashboard/How-to-Navigate-Kalp-Studio-Platform-as-a-New-User.md'
          - How to Navigate Kalp Studio Dashboard as an Active User: 'Getting-started/Dashboard/How-to-Navigate-Kalp-Studio-Dashboard-as-an-Active-User.md'
      - Billing:
          - How does a new user access billing: 'Getting-started/Billing/How-does-a-new-user-access-billing.md'
          - How does a subscribed user access billing: 'Getting-started/Billing/How-does-a-subscribed-user-access-billing.md'
          - How does Billing work on the Kalp Studio Platform: 'Getting-started/Billing/How-does-Billing-work-on-the-Kalp-Studio-Platform.md'
      - Credits:
          - How to Add Credit: 'Getting-started/Credits/How-to-Add-Credit.md'
          - Navigate to the credit section: 'Getting-started/Credits/Navigate-to-the-Credit-Section.md'
      - Kalp-studio-wallet:
          - How to Navigate To kalp studio Wallet: 'Getting-started/Kalp-studio-wallet/How-to-Navigate-To-kalp-studio-Wallet.md'
          - How to Create and Connect Wallet to Kalp Studio: 'Getting-started/Kalp-studio-wallet/How-to-Create-and-Connect-Wallet-to-Kalp-Studio.md'
      - Kalp Instant Deployer:
          - How to Deploy a Smart Contract on Kalp Studio: 'Getting-started/Kalp-Instant-Deployer/How-to-Deploy-a-Smart-Contract-on-Kalp-Studio.md'
      - API Gateway:
          - How to generate API endpoints: 'Getting-started/API-Gateway/How-to-generate-API-endpoints.md'
          - How to navigate to the list of smart contract: 'Getting-started/API-Gateway/How-to-Navigate-to-the-List-of-Smart-Contract.md'
      - API Key Generation:
          - How to generate API Key: 'Getting-started/API-Key-Generation/How-to-generate-API-Key.md'
      - Transaction monitoring:
          - How can I monitor all my transactions: 'Getting-started/Transaction-monitoring/How-can-I-monitor-all-my-transactions.md'
      - Settings:
          - How to Process KYC and get purchased template list: 'Getting-started/Settings/How-to-Process-KYC-and-get-purchased-template-list.md'
  - Dev documentation:
      - Use the kalp SDK:
          - Kalp Golang SDK: 'Dev-documentation/Use-the-kalp-sdk/Kalp-golang-sdk.md'
      - KRC Token Standard:
          - KRC 20 Token Contract: 'Dev-documentation/KRC-Token-Standard/KRC-20-Token-Contract.md'
          - KRC 721 Token Contract: 'Dev-documentation/KRC-Token-Standard/KRC-721-Token-Contract.md'
          - KRC 1155 Token Contract: 'Dev-documentation/KRC-Token-Standard/KRC-1155-Token-Contract.md'
      - Smart Contract Write,Test, Deploy & Interact:
          - Write the smart contract: 'Dev-documentation/Smart-Contract-Write-Test-Deploy-Interact/Write-the-smart-contract.md'
          - Test the smart contract: 'Dev-documentation/Smart-Contract-Write-Test-Deploy-Interact/Test-the-smart-contract.md'
          - Deploy the smart contract: 'Dev-documentation/Smart-Contract-Write-Test-Deploy-Interact/Deploy-the-smart-contract.md'
          - Interacting with smart contract: 'Dev-documentation/Smart-Contract-Write-Test-Deploy-Interact/Interacting-with-smart-contract.md'
  - Release notes:
      - Release version 2.0.0:
          - Release notes version 2.0.0: 'Release-notes/release-version-2.0.0/release-notes-version-2.0.0.md'
      - Release version 1.1.1:
          - Release notes version 1.1.1: 'Release-notes/release-version-1.1.1/release-notes-version-1.1.1.md'
      - Release version 1.1.0:  
          - Release notes version 1.1.0: 'Release-notes/release-version-1.1.0/release-notes-version-1.1.0.md'
      - Release version 1.0.0:
          - Release notes version 1.0.0: 'Release-notes/release-version-1.0.0/release-notes-version-1.0.0.md'    
extra:
  social:

    - icon: fontawesome/brands/github
      link: https://github.com/thekalpstudio/
  
    - icon: fontawesome/brands/x-twitter 
      link: https://twitter.com/Kalp_Studio

    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/people/Kalp-Studio/61558481045861/

    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/kalpstudio.official/

    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/studio-kalp/

    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/JhD7GFVvfv

  generator: false