site_name: Kalp Studio Documentation
site_author: Siddhesh Patankar
repo_name: Kalp studio knowledge layer
copyright: Copyright 2024 Kalp studio. All rights reserved.
repo_url: https://github.com/siddheshp2e/Technical_Documentation

theme:
  font: 
    code: Poppins
  name: material
  logo: images/PNG.png
  favicon: images/PNG.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - header.bold
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.prune
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.leftside
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      scheme: default
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      accent: deep orange 
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/eye-outline
        name: Switch to system preference
  plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: false
  - search
  - open-in-new-tab
  - git authors
  
  markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.codehilite:
  - pymdownx.inlinehilite:
  pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

extra:
  social:

    - icon: fontawesome/brands/github
      link: https://github.com
  
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/kalpstudio

    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/@kalpstudio

    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/@kalpstudio

    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/@kalpstudio

    - icon: fontawesome/brands/discord
      link: https://discord.com/@kalpstudio

  generator: false

  nav: 
    - Introduction:
      - Welcome.md
